### PR TITLE
issues7 | createAddXml in CompatibilityLayer

### PR DESCRIPTION
**Pull request by GZyl**
issue 7 
Add methods removed attributes

### CODE REVIEW

**Comment by rjkip** [comment]
Hi @GZyl,

Thanks a lot for your contribution. You did a good job. I have opted not to break backwards compatibility. Based on your implementation and tests, I have implemented a solution in #9. Could you review this and confirm that this solves #7?

Thanks!

**Comment by GZyl** [comment]
;] #9 solves #7 but it is a little more complicated (We can use it).

There was backwards compatibility 
We made test on solr 3.6 and solr 4.7.

**Comment by rjkip** [comment]
Backwards compatibility was broken in case someone implemented their own comp layer. Not likely, but a BC break nonetheless. So you agree on merging #9?

**Comment by GZyl** [comment]
I agree.

**Pull request closed without merging**
