### PR TITLE
Fix: system servlet for Solr 4.4 and above

### PR DESCRIPTION
**Pull request by luxifer**

### CODE REVIEW

**Comment by rjkip** [comment]
I don't use the system info. Why was this changed in 4.4+? Does `admin/system` still exist? How does this affect <4.4 users?

**Comment by luxifer** [comment]
The `admin/system` does not exist anymore, it's a BC break since solr 4.4. So i suggest to make a tag in this repo and write on the readme it's for solr <4.4 if you want to merge this PR. In solr 4.4 and above the `admin/system` is replaced by `admin/info/system`, but it's exactly the same json.

**Comment by rjkip** [comment]
Sorry for the slow response. What about a configurable info URL so I don't have to do something radical like a new major release?

**Comment by luxifer** [comment]
It could be a great alternative, i'll make the changes in this PR

**Comment by luxifer** [comment]
Done in #10

**Pull request closed without merging**
